#!/usr/bin/env bash
set -euo pipefail

# Fill iosApp/Configuration/Config.local.xcconfig from Apple Development
# and Developer ID certificates in the login keychain. Does not fail the
# Xcode build when the keychain has no matching certs (simulator still runs).

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/ios-codesign-identities.sh
. "$ROOT/scripts/lib/ios-codesign-identities.sh"

LOCAL_XCCONFIG="$ROOT/iosApp/Configuration/Config.local.xcconfig"

load_identity_dump() {
  if [ -n "${IOS_CODESIGN_IDENTITIES_FILE:-}" ]; then
    cat "$IOS_CODESIGN_IDENTITIES_FILE"
    return 0
  fi
  dump_login_codesign_identities
}

write_local_xcconfig() {
  local team_id="$1"
  local identity="$2"
  local source="$3"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp" <<EOF
// Generated by scripts/sync-ios-signing.sh — do not commit.
// Source: ${source}
// Identity: ${identity}
TEAM_ID = ${team_id}
CODE_SIGN_IDENTITY = Apple Development
EOF
  mv "$tmp" "$LOCAL_XCCONFIG"
}

print_missing_certs() {
  echo "No Apple Development or Developer ID certificate in the login keychain."
  echo "Simulator Run still works. For a device, install a development cert in login and re-run."
}

sync_from_identities() {
  local dump selected team_id source identity
  if ! dump="$(load_identity_dump)"; then
    echo "Could not read codesigning identities from the login keychain."
    echo "Left ${LOCAL_XCCONFIG} unchanged (if it exists)."
    return 0
  fi
  if ! selected="$(printf '%s\n' "$dump" | select_ios_signing)"; then
    print_missing_certs
    return 0
  fi
  team_id="$(printf '%s\n' "$selected" | sed -n 's/^TEAM_ID=//p')"
  source="$(printf '%s\n' "$selected" | sed -n 's/^SOURCE=//p')"
  identity="$(printf '%s\n' "$selected" | sed -n 's/^IDENTITY=//p')"
  write_local_xcconfig "$team_id" "$identity" "$source"
  echo "Wrote $LOCAL_XCCONFIG"
  echo "  TEAM_ID=$team_id"
  echo "  from $identity"
  printf '%s\n' "$selected" | sed -n 's/^WARNING=//p' | while IFS= read -r warning; do
    echo "  warning: $warning"
  done
}

sync_from_identities
